services:
  nozerodays.api:
    image: ${DOCKER_REGISTRY-}nozerodays.api
    build:
      context: .
      dockerfile: NoZeroDays.Api/Dockerfile
    ports:
      - 5248:8080
      - 7046:8081
    environment:
      - ConnectionStrings__DefaultConnection=Server=nozerodays.mysql;Port=3306;Database=zero_db;User=app;Password=root;
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://nozerodays.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    depends_on:
      nozerodays.mysql:
        condition: service_healthy

  nozerodays.mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-root}
      MYSQL_DATABASE: zero_db
      MYSQL_USER: app
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-root}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD-root}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
  
  
  nozerodays.seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341

  nozerodays.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
    
volumes:
  mysql-data: